language: python
before_install:
- npm install -g bower grunt-cli
install:
- pip install -r requirements.txt
after_success:
- cd etc
- npm install
- bower install
- python manage.py collectstatic --noinput
- grunt
 
python:
- "2.7"
- "2.6"
script: "python manage.py test daw.tests"
